FROM golang:1.10-alpine AS builder
RUN apk update
RUN apk add --no-cache build-base bash git
COPY . /go/src/github.com/kaizhe/echo
WORKDIR /go/src/github.com/kaizhe/echo
RUN make all

FROM alpine
RUN apk update && apk add ca-certificates netcat && rm -rf /var/cache/apk/*
ADD --from=builder /go/src/github.com/kaizhe/echo/echo /echo
LABEL multi.label1="value1" multi.label2="value2" other="value3"
ENV AWS_ACCESS_KEY_ID xxx
ENV AWS_SECRET_ACCESS_KEY=yyy
USER 0:0
ENTRYPOINT ["/echo"]
