FROM golang:1.10-alpine AS builder
RUN apk add --no-cache build-base bash git
COPY . /go/src/github.com/kaizhe/echo
WORKDIR /go/src/github.com/kaizhe/echo
RUN make all

FROM alpine
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY --from=builder /go/src/github.com/kaizhe/echo/echo /echo
USER echo
HEALTHCHECK --interval=5m --timeout=3s \
              CMD curl -f http://www.google.com/ || exit 1
ENTRYPOINT ["/echo"]
